### ISSUE TITLE
github actionsのbackendのtestが失敗する

### ISSUE THREAD

**Issue by suimenkathemove** [emgniddikur/slack-clone#6]
## Overview

```
POSTGRES_USER
POSTGRES_PASSWORD
POSTGRES_DB
```
cargo-makeで設定している環境変数がセットできていないために発生していると思われる。
localでは問題ない。
docker-compose.ymlで以下の設定をすると通る。
```yml
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monorepo_sandbox
```
